php:
  build: .
  dockerfile: ./docker/php/Dockerfile
  container_name: blog-comment_php
  volumes:
    - .:/var/www/blog

nginx:
  image: nginx:alpine
  container_name: blog-comment_nginx
  volumes_from:
    - php
  volumes:
    - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 8090:80



